on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  update-id:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update app ID in manifest.json to production
        run: |
          sed -i 's/"id": "cargaarchivoexcel"/"id": "cargaarchivoexcel-production"/' webapp/manifest.json

      - name: Update MTA ID to production
        run: |
          sed -i 's/^ID: cargaarchivoexcel$/ID: cargaarchivoexcel-production/' mta.yaml

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add webapp/manifest.json mta.yaml
          git commit -m "Update app and MTA ID to production after merge" || echo "No changes to commit"
          git push origin main
